# Generated by Django 5.1.3 on 2025-02-05 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_options_alter_giornalista_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 5, 10, 41, 38, 498439)),
        ),
        migrations.AddField(
            model_name='articolo',
            name='visualizzazioni',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 5, 10, 41, 38, 498439), max_length=10),
        ),
    ]
