# Generated by Django 5.1.3 on 2025-02-12 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_articolo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 4, 31, 42129)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 4, 31, 42129), max_length=10),
        ),
    ]
