# Generated by Django 5.1.3 on 2025-02-12 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('descrizione', models.TextField(max_length=30)),
                ('data_inizio', models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 51, 55, 467225), max_length=10)),
                ('data_fine', models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 51, 55, 467225), max_length=10)),
                ('posti_disponibili', models.IntegerField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 51, 55, 467225), max_length=10)),
            ],
        ),
    ]
