# Generated by Django 5.1.3 on 2025-02-12 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 56, 20, 612309), max_length=10),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 56, 20, 612309), max_length=10),
        ),
        migrations.AlterField(
            model_name='corso',
            name='posti_disponibili',
            field=models.IntegerField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 56, 20, 612309), max_length=10),
        ),
    ]
