# Generated by Django 5.1.3 on 2025-02-12 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0003_alter_corso_data_fine_alter_corso_data_inizio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 5, 5, 593890), max_length=20),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 5, 5, 593890), max_length=20),
        ),
        migrations.AlterField(
            model_name='corso',
            name='posti_disponibili',
            field=models.IntegerField(blank=True, default=datetime.datetime(2025, 2, 12, 10, 5, 5, 593890), max_length=10),
        ),
    ]
